name: Compile & Run (plain javac)

on: [push, pull_request]

jobs:
  build-and-run:
    runs-on: macos-latest   # JavaFX SDK we fetch below is for macOS arm64
    env:
      JAVA_VERSION: '17'
      JAVAFX_VERSION: '17.0.12'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Temurin JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}

      - name: Prepare dirs
        run: mkdir -p out lib

      - name: Download JavaFX SDK
        run: |
          curl -L -o lib/javafx.zip \
            https://download2.gluonhq.com/openjfx/${JAVAFX_VERSION}/openjfx-${JAVAFX_VERSION}_osx-aarch64_bin-sdk.zip
          unzip -q lib/javafx.zip -d lib
          echo "JAVAFX_LIB=$PWD/lib/javafx-sdk-${JAVAFX_VERSION}/lib" >> $GITHUB_ENV

      - name: Compile sources (skip *Test.java)
        run: |
          SRC_FILES=$(ls *.java 2>/dev/null | grep -v "Test.java" || true)
          if [ -z "$SRC_FILES" ]; then
            echo "No non-test sources found."
            exit 1
          fi
          javac --module-path "$JAVAFX_LIB" --add-modules javafx.controls,javafx.fxml \
                -d out $SRC_FILES

      - name: Try to run a main class (if any)
        run: |
          # Find the first .java file that declares a main method and use its class name
          MAIN_CLASS=$(grep -l "static void main\s*(" *.java | head -n 1 | sed 's/.java$//')
          if [ -z "$MAIN_CLASS" ]; then
            echo "No class with 'public static void main' found. Build succeeded."
            exit 0
          fi
          echo "Running $MAIN_CLASS ..."
          java --module-path "$JAVAFX_LIB" --add-modules javafx.controls,javafx.fxml \
               -cp out "$MAIN_CLASS"
