name: JUnit Tests (plain javac)

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Temurin JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install JavaFX (OpenJFX) via Homebrew
        run: |
          brew update
          brew install openjfx
          echo "JFX_LIB=$(brew --prefix)/opt/openjfx/lib" >> $GITHUB_ENV

      - name: Download JUnit Console & org.json
        run: |
          mkdir -p lib
          curl -L -o lib/junit-console.jar \
            https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.11.3/junit-platform-console-standalone-1.11.3.jar
          curl -L -o lib/json.jar \
            https://repo1.maven.org/maven2/org/json/json/20240303/json-20240303.jar

      - name: Compile sources & tests
        shell: bash
        run: |
          mkdir -p out
          # All .java files (src + tests in repo root)
          SRC_FILES=$(ls *.java 2>/dev/null || true)
          if [ -z "$SRC_FILES" ]; then
            echo "No .java files found in repo root."
            exit 1
          fi

          javac \
            --release 17 \
            --module-path "$JFX_LIB" \
            --add-modules javafx.controls,javafx.fxml \
            -cp "lib/junit-console.jar:lib/json.jar" \
            -d out \
            $SRC_FILES

      - name: Create CI bootstrap to init JavaFX (not added to repo)
        shell: bash
        run: |
          cat > out/CiTestRunner.java <<'EOF'
          public class CiTestRunner {
            public static void main(String[] args) throws Exception {
              // Headless JavaFX on CI
              System.setProperty("javafx.platform", "Monocle");
              System.setProperty("monocle.platform", "Headless");
              System.setProperty("prism.order", "sw");
              // Trigger toolkit init without changing project code
              new javafx.embed.swing.JFXPanel();
              // Delegate to JUnit Console to run all tests on classpath
              org.junit.platform.console.ConsoleLauncher.main(new String[]{"--scan-class-path"});
            }
          }
          EOF
          # Compile the bootstrap against already compiled classes
          javac \
            --release 17 \
            --module-path "$JFX_LIB" \
            --add-modules javafx.controls,javafx.fxml \
            -cp "out:lib/junit-console.jar:lib/json.jar" \
            -d out \
            out/CiTestRunner.java
          rm out/CiTestRunner.java

      - name: Run tests (headless JavaFX)
        shell: bash
        run: |
          java \
            --module-path "$JFX_LIB" \
            --add-modules javafx.controls,javafx.fxml \
            -cp "out:lib/junit-console.jar:lib/json.jar" \
            CiTestRunner
