name: JUnit Tests (plain javac)

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      JFX_VERSION: "17.0.12"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Temurin JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Xvfb and GTK deps (for JavaFX)
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libgtk-3-0 libxext6 libxi6 libxtst6 libasound2 libgl1-mesa-glx

      - name: Download JavaFX SDK (Linux x64)
        run: |
          curl -L -o openjfx.zip \
            https://download2.gluonhq.com/openjfx/${JFX_VERSION}/openjfx-${JFX_VERSION}_linux-x64_bin-sdk.zip
          unzip -q openjfx.zip
          echo "JFX_LIB=$PWD/javafx-sdk-${JFX_VERSION}/lib" >> $GITHUB_ENV

      - name: Download JUnit Console & org.json
        run: |
          mkdir -p lib
          curl -L -o lib/junit-console.jar \
            https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.11.3/junit-platform-console-standalone-1.11.3.jar
          curl -L -o lib/json.jar \
            https://repo1.maven.org/maven2/org/json/json/20240303/json-20240303.jar

      - name: Compile sources & tests
        shell: bash
        run: |
          mkdir -p out
          SRC_FILES=$(ls *.java 2>/dev/null || true)
          if [ -z "$SRC_FILES" ]; then
            echo "No .java files found in repo root."
            exit 1
          fi
          javac \
            --release 17 \
            --module-path "$JFX_LIB" \
            --add-modules javafx.controls,javafx.fxml,javafx.graphics \
            -cp "lib/junit-console.jar:lib/json.jar" \
            -d out \
            $SRC_FILES

      - name: Bootstrap JavaFX then run JUnit (headless via Xvfb)
        shell: bash
        run: |
          # small bootstrap to init JavaFX Toolkit before JUnit scans classpath
          cat > out/CiTestRunner.java <<'EOF'
          import javafx.application.Platform;
          public class CiTestRunner {
            public static void main(String[] args) {
              final Object lock = new Object();
              synchronized (lock) {
                Platform.startup(() -> { synchronized (lock) { lock.notify(); } });
                try { lock.wait(); } catch (InterruptedException ignored) {}
              }
              org.junit.platform.console.ConsoleLauncher.main(new String[] {"--scan-class-path"});
            }
          }
          EOF

          javac \
            --release 17 \
            --module-path "$JFX_LIB" \
            --add-modules javafx.controls,javafx.fxml,javafx.graphics \
            -cp "out:lib/junit-console.jar:lib/json.jar" \
            -d out \
            out/CiTestRunner.java

          # run under a virtual X display so JavaFX can open a toolkit
          xvfb-run -a \
          java \
            --module-path "$JFX_LIB" \
            --add-modules javafx.controls,javafx.fxml,javafx.graphics \
            -cp "out:lib/junit-console.jar:lib/json.jar" \
            CiTestRunner
